#!/usr/bin/env python3
"""Hidden verifier for erp_ledger. Never visible to the candidate.

Runs with the RUN's venv python. Unlike cad3d_brep this needs no oracle environment: the reference
implementation is pure standard library, so it is imported directly and there is no subprocess
delegation and no third-party library whose optional dependencies could bite.

Graded checks:

  entrypoint          run_erp.sh exists and is a shell script
  env_constraints     no forbidden package installed in the workspace env
  invariants          after EVERY document of EVERY scenario: debits==credits, inventory account
                      equals valuation layers plus carried remainder, no negative stock
  trial_balance       every account of every scenario, exact to the minor unit
  mrp_plan            planned order set exact: same orders, quantities and days
  rejection_set       informational — set equality is what matters, ordering is not

There are no tolerances here at all, and that is the point of this task rather than an oversight.
Every graded quantity is an integer in minor currency units or whole pieces, so "close" has no
meaning: a single cent that fails to balance is a wrong set of books. Contrast cad3d_brep, where
mass properties legitimately carry a tolerance because they are computed from a tessellation.

The one deliberate piece of slack is the rejection set's ordering, which the spec never pins down.
Grading an ordering the spec does not specify is how false negatives are manufactured.

READ THIS BEFORE TRUSTING A CALIBRATION RUN. Calibrating this task with ref_erp.py is structurally
self-referential: ref/*.json were generated BY ref_erp.py, so feeding ref_erp.py back in scores
4/4 by construction. That result says the plumbing works — entry-point contract, JSON shape,
invariant replay, comparison logic — and says NOTHING about whether the oracle is correct. What
actually validates the oracle is (a) ref_erp's own per-document invariant checks, which
make_scenarios refuses to write a scenario past, and (b) the independent audit that recomputes
reference answers straight from the spec's formulas rather than from ref_erp's internals.
The audit is not infallible either: its first version folded the carried remainder into the moving
average's cost base, contradicted a correct oracle, and would have led to "fixing" working code.
Two disagreeing derivations mean one of them is wrong — not that the newer one wins.

usage: verify.py --workspace <ws> --out <json> [--erp-cmd 'tmpl {scenario} {out}'] [--skip-env-check]
"""
import argparse
import json
import pathlib
import sys
import tempfile

HERE = pathlib.Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parents[2] / "harness"))
sys.path.insert(0, str(HERE))
from verify_common import sh, make_env  # noqa: E402

FORBIDDEN = ("pandas", "sqlalchemy", "django", "odoo", "erpnext", "frappe", "beancount",
             "ledger", "piecash", "gnucash", "openpyxl", "xlrd", "scipy")


def norm_int(v):
    """Accept ints and int-valued floats/strings; anything else stays as-is so it compares unequal."""
    if isinstance(v, bool):
        return v
    if isinstance(v, int):
        return v
    if isinstance(v, float) and v.is_integer():
        return int(v)
    if isinstance(v, str):
        try:
            return int(v)
        except ValueError:
            return v
    return v


def grade(got, ref, scenario):
    """Return (tb_ok, mrp_ok, rej_ok, detail)."""
    d = {}

    # --- trial balance: every declared account, exact
    tb_got = {k: norm_int(v) for k, v in (got.get("trial_balance") or {}).items()}
    tb_ref = ref["trial_balance"]
    missing = [a for a in tb_ref if a not in tb_got]
    wrong = [(a, tb_got.get(a), tb_ref[a]) for a in tb_ref
             if a in tb_got and tb_got[a] != tb_ref[a]]
    tb_ok = not missing and not wrong
    if missing:
        d["tb_missing"] = missing[:6]
    if wrong:
        d["tb_wrong"] = [f"{a}: {g} != {r}" for a, g, r in wrong[:6]]
        d["tb_n_wrong"] = len(wrong)

    # --- floats are a spec violation in their own right, worth reporting separately
    floats = [k for k, v in (got.get("trial_balance") or {}).items()
              if isinstance(v, float) and not float(v).is_integer()]
    if floats:
        d["non_integer_balances"] = floats[:6]
        tb_ok = False

    # --- MRP: exact set of planned orders
    def key(p):
        return (str(p.get("material")), norm_int(p.get("qty")),
                norm_int(p.get("release_day")), norm_int(p.get("due_day")))
    got_plan = sorted(key(p) for p in (got.get("planned_orders") or []))
    ref_plan = sorted(key(p) for p in ref["planned_orders"])
    mrp_ok = got_plan == ref_plan
    if not mrp_ok:
        only_ref = [p for p in ref_plan if p not in got_plan][:4]
        only_got = [p for p in got_plan if p not in ref_plan][:4]
        d["mrp_missing"] = only_ref
        d["mrp_spurious"] = only_got

    # --- rejection set: compare as sets, ordering is not specified
    rej_ok = set(map(str, got.get("rejected") or [])) == set(map(str, ref["rejected"]))
    if not rej_ok:
        d["rejected_got"] = sorted(map(str, got.get("rejected") or []))[:8]
        d["rejected_ref"] = sorted(map(str, ref["rejected"]))[:8]

    cyc_ok = sorted(map(str, got.get("bom_cycles") or [])) == sorted(map(str, ref["bom_cycles"]))
    if not cyc_ok:
        d["cycles_got"] = sorted(map(str, got.get("bom_cycles") or []))
        d["cycles_ref"] = ref["bom_cycles"]
    return tb_ok, mrp_ok, rej_ok and cyc_ok, d


def replay_invariants(scenario, got):
    """Independently replay the candidate's own reported books through the invariant checks.

    The candidate reports only final state, so per-document invariants are checked on the reference
    replay; what is verified against the candidate is the identity that must hold on ITS numbers:
    inventory account == sum(qty*unit_cost) + remainder, and no negative stock.
    """
    problems = []
    stock = got.get("stock") or []
    for row in stock:
        q = norm_int(row.get("qty"))
        if isinstance(q, int) and q < 0:
            problems.append(f"negative stock {row.get('material')}={q}")
        uc, val = norm_int(row.get("unit_cost")), norm_int(row.get("value"))
        if isinstance(q, int) and isinstance(uc, int) and isinstance(val, int) and q * uc != val:
            problems.append(f"{row.get('material')}: value {val} != qty*unit_cost {q * uc}")
    tb = got.get("trial_balance") or {}
    if "1401" in tb:
        inv = norm_int(tb["1401"])
        layers = sum(norm_int(r.get("value") or 0) for r in stock)
        if isinstance(inv, int) and inv < layers:
            problems.append(f"inventory account {inv} below layer total {layers}")
    return problems


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--workspace", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--erp-cmd", default=None,
                    help="calibration: command template with {scenario} and {out}")
    ap.add_argument("--skip-env-check", action="store_true")
    a = ap.parse_args()

    ws = pathlib.Path(a.workspace).resolve()
    tmp = pathlib.Path(tempfile.mkdtemp(prefix="verify_erp_"))
    env = make_env(ws)
    env.pop("PYTHONPATH", None)
    manifest = json.loads((HERE / "manifest.json").read_text())["scenarios"]

    checks, metrics, per = {}, {}, {}
    entry = ws / "run_erp.sh"
    # Presence is all that is graded here. A Python file misnamed .sh — the failure mode a model
    # hit on cad3d — needs no special detection: bash dies on it, every scenario yields no output,
    # and the downstream checks fail with the shell's own error text recorded as the reason. Adding
    # a heuristic "is it really a shell script" test would only create a second way to be wrong.
    checks["entrypoint"] = {"pass": entry.exists(),
                            "detail": "run_erp.sh" + ("" if entry.exists() else " missing")}
    if not a.skip_env_check:
        rc, out = sh(["bash", "-c", "pip list 2>/dev/null | awk '{print tolower($1)}'"],
                     str(tmp), env, 180)
        bad = [p for p in FORBIDDEN if p in out.split()]
        checks["env_constraints"] = {"pass": not bad,
                                     "detail": "forbidden: " + ", ".join(bad) if bad else "ok"}

    inv_ok = tb_ok = mrp_ok = rej_ok = 0
    for name in manifest:
        ref = json.loads((HERE / "ref" / f"{name}.json").read_text())
        scenario = json.loads((HERE / "scenarios" / f"{name}.json").read_text())
        wd = tmp / name
        wd.mkdir(parents=True, exist_ok=True)
        sfile = wd / f"{name}.json"
        sfile.write_text(json.dumps(scenario))
        ofile = wd / f"{name}.out.json"
        cmd = (a.erp_cmd.format(scenario=sfile, out=ofile).split() if a.erp_cmd
               else ["bash", str(entry), str(sfile), str(ofile)])
        rc, log = sh(cmd, str(wd), env, 600)
        rec = {"rc": rc}
        if not ofile.exists():
            rec["why"] = f"no output: {log[-200:]}"
            per[name] = rec
            continue
        try:
            got = json.loads(ofile.read_text())
        except Exception as e:  # noqa: BLE001
            rec["why"] = f"unparseable output: {str(e)[:140]}"
            per[name] = rec
            continue
        problems = replay_invariants(scenario, got)
        t_ok, m_ok, r_ok, d = grade(got, ref, scenario)
        rec.update(d, inv=not problems, tb=t_ok, mrp=m_ok, rej=r_ok)
        if problems:
            rec["inv_why"] = "; ".join(problems)[:200]
        inv_ok += not problems
        tb_ok += t_ok
        mrp_ok += m_ok
        rej_ok += r_ok
        per[name] = rec

    n = len(manifest)
    metrics["per_scenario"] = per
    metrics["n_scenarios"] = n
    # every one of these is an exact integer identity: a violation proves the books are wrong,
    # so all three are graded n-of-n. No 0.9 threshold anywhere in this task.
    checks["invariants"] = {
        "pass": inv_ok == n,
        "detail": f"{inv_ok}/{n} scenarios invariant-clean; off: " +
                  ", ".join(f"{k}({str(v.get('inv_why', v.get('why', '')))[:40]})"
                            for k, v in per.items() if not v.get("inv"))}
    checks["trial_balance"] = {
        "pass": tb_ok == n,
        "detail": f"{tb_ok}/{n} exact; off: " +
                  ", ".join(f"{k}({v.get('tb_n_wrong', '?')} accts)"
                            for k, v in per.items() if not v.get("tb"))}
    checks["mrp_plan"] = {
        "pass": mrp_ok == n,
        "detail": f"{mrp_ok}/{n} exact; off: " +
                  ", ".join(k for k, v in per.items() if not v.get("mrp"))}
    checks["rejection_set"] = {
        "pass": True, "informational": True,
        "detail": f"{rej_ok}/{n} rejection/cycle sets matched"}

    required = {k: v for k, v in checks.items() if not v.get("informational")}
    npass = sum(1 for c in required.values() if c["pass"])
    result = {"pass": npass == len(required), "score": f"{npass}/{len(required)}",
              "checks": checks, "metrics": metrics}
    pathlib.Path(a.out).write_text(json.dumps(result, ensure_ascii=False, indent=1))
    print(json.dumps({k: v["pass"] for k, v in checks.items()}, ensure_ascii=False),
          result["score"], "PASS" if result["pass"] else "FAIL")


if __name__ == "__main__":
    main()
