#!/bin/bash
set -e
WS=$1; HERE=$(cd "$(dirname "$0")" && pwd)
mkdir -p "$WS/examples"; cp "$HERE/hidden/SPEC.md" "$WS/SPEC.md"
python3 - "$HERE" "$WS" <<'PY'
import sys, json, pathlib
here, ws = pathlib.Path(sys.argv[1]), pathlib.Path(sys.argv[2]); sys.path.insert(0, str(here / "hidden")); import nist_parse
for name in ("Norris", "Pontius", "Longley", "Misra1a", "MGH09", "SiRstv"):   # visible examples with certified answers
    d = nist_parse.parse(here / "hidden" / "data" / f"{name}.dat"); csv, syn = nist_parse.to_syntax(d)
    ex = ws / "examples" / name; ex.mkdir(parents=True); (ex / "data.csv").write_text(csv); (ex / "script.sps").write_text(syn)
    cert = {k: v for k, v in d.items() if k.startswith("cert")} | {"difficulty": d["difficulty"], "kind": d["kind"]}
    (ex / "certified.json").write_text(json.dumps(cert, indent=1))
PY
cat > "$WS/ENVIRONMENT.md" <<'EON'
# Target environment (fixed)
`python` on PATH is Python 3.12 with NumPy and pytest only. You may not install SciPy, statsmodels, scikit-learn, pandas, lmfit,
patsy or any other statistics/optimisation library (verification checks the environment); implement the numerics yourself.
EON
cat > "$WS/README.md" <<'EON'
# statsx
Clean-room statistical engine. Read SPEC.md (syntax, JSON output, accuracy targets). examples/<name>/ contain a data.csv, a
script.sps and the certified answers for that problem; the hidden evaluation uses the same syntax on 43 NIST StRD problems
of lower/average/higher difficulty (linear/polynomial regression incl. 10th-degree polynomials, nonlinear regression from
given starting values, one-way ANOVA).
EON
# a skill generated by LabAgent may be injected here by the harness (condition "labagent")
